### ISSUE TITLE
希望能记录点击位置

### ISSUE THREAD

**Issue by TwilightKHQ** [runhey/Uowl#2]
希望能和[[aicezam / SmartOnmyoji](https://github.com/aicezam/SmartOnmyoji)] 一样记录点击位置

**Comment by runhey** [comment]
好主意！

**Comment by runhey** [comment]
可以这么做，首先开启本地日志，可以再写一个工具从本地日志中提取信息从而生成点击图

**Comment by runhey** [comment]
> 希望能和[[aicezam / SmartOnmyoji](https://github.com/aicezam/SmartOnmyoji)] 一样记录点击位置

脚本设置处开启
然后每运行一个task便会生成一个txt日志文件和一个坐标数据文件csv 文件位置根目录/Log
在根目录/Tools/PositionAanalysis/ 有一个脚本运行即可看到位置图
